version: 2.1
jobs:
  phpstan:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: cobiro/php:8.0-develop
      - image: wiremock/wiremock:latest
        name: wiremock
    steps:
    - checkout
    - restore_cache: {keys: ['v1-dependencies-{{ checksum "composer.lock" }}', v1-dependencies-]}
    - run: composer install -n -a
    - save_cache: {paths: [vendor], key: 'v1-dependencies-{{ checksum "composer.lock" }}'}
    - run:
        name: Run static code analysis
        command: vendor/bin/phpstan
  test_unit:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: cobiro/php:8.0-develop
      - image: wiremock/wiremock:latest
        name: wiremock
    steps:
      - checkout
      - restore_cache: {keys: ['v1-dependencies-{{ checksum "composer.lock" }}', v1-dependencies-]}
      - run: composer install -n -a
      - save_cache: {paths: [vendor], key: 'v1-dependencies-{{ checksum "composer.lock" }}'}
      - run: # for some reason some repositories require this configuration
          name: Configure proper working directory for pcov
          command: echo pcov.directory=/root/repo >> "$PHP_INI_DIR/conf.d/pcov.ini"
      - run:
          name: run unit tests
          command: |
            php vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover coverage-clover/clover-unit.xml --log-junit ~/phpunit/unit-junit.xml --testdox
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
  test_integration_1:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: cobiro/php:8.0-develop
      - image: wiremock/wiremock:latest
        name: wiremock
    steps:
      - checkout
      - restore_cache: {keys: ['v1-dependencies-{{ checksum "composer.lock" }}', v1-dependencies-]}
      - docker/install-dockerize
      - run: composer install -n -a
      - save_cache: {paths: [vendor], key: 'v1-dependencies-{{ checksum "composer.lock" }}'}
      - run: # for some reason some repositories require this configuration
          name: Configure proper working directory for pcov
          command: echo pcov.directory=/root/repo >> "$PHP_INI_DIR/conf.d/pcov.ini"
      - run:
          name: run unit tests
          command: |
            php vendor/bin/phpunit --configuration=phpunit.verification-extension.xml --coverage-clover coverage-clover/clover-unit.xml --log-junit ~/phpunit/unit-junit.xml --testdox
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
  test_integration_2:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: cobiro/php:8.0-develop
      - image: wiremock/wiremock:latest
        name: wiremock
    steps:
      - checkout
      - restore_cache: {keys: ['v1-dependencies-{{ checksum "composer.lock" }}', v1-dependencies-]}
      - run: composer install -n -a
      - save_cache: {paths: [vendor], key: 'v1-dependencies-{{ checksum "composer.lock" }}'}
      - run: # for some reason some repositories require this configuration
          name: Configure proper working directory for pcov
          command: echo pcov.directory=/root/repo >> "$PHP_INI_DIR/conf.d/pcov.ini"
      - run:
          name: run unit tests
          command: |
            php vendor/bin/phpunit --configuration=phpunit.non-verification-extension.xml --coverage-clover coverage-clover/clover-unit.xml --log-junit ~/phpunit/unit-junit.xml --testdox
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

workflows:
  version: 2

  test:
    jobs:
      - phpstan
      - test_unit
      - test_integration_1
      - test_integration_2
